name: "Android CI"

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Build & Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Source
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v5.4.0
        with:
          distribution: temurin
          java-version: 17

      - name: Build & Test
        run: ./gradlew build test